### PR TITLE
Added normalisation and unit test cases

### PR DESCRIPTION
**Pull request by sritha272**
## Description

Implemented multiple data transformation functions (normalize, scale, clipping, exponential, standardize, z_score_normalize) to enhance the framework's data processing capabilities. These functions are equipped with comprehensive unit tests to ensure correctness and handle edge cases.
**Breakdown of Each Implemented Function**
- **Normalize**
  Scales data to a specified range [min_value, max_value].
  Includes edge case handling for zero range and empty data.

- **Scale**
   Scales data by a specified multiplier.
   Useful for linear scaling transformations.

- **Clipping**
  Clips data to fall within a specified range [min_value, max_value].
  Prevents extreme outliers in datasets.

- **Exponential Transformation**
  Applies an exponential transformation to data with a specified base.
  Handles exponential growth scenarios effectively.

- **Standardize**
Standardizes data to have a mean of 0 and a standard deviation of 1.
Includes custom mean and standard deviation parameters.

- **Z-Score Normalize**
Computes z-scores for data points for standardization.
Handles mixed positive and negative datasets effectively.

## Motivation and Context

The newly added functions provide robust data normalization and transformation capabilities, which are critical for preparing data for machine learning, statistical analysis, and other computational tasks. These functions solve the problem of inconsistent data scaling and ensure uniform preprocessing pipelines.

## How Has This Been Tested?

- **Unit Tests**: Added unit tests for each function:
  Verified outputs for standard, edge, and invalid inputs.
  Tests include large numbers, small numbers, mixed data types, and edge cases like empty datasets or identical values.

- **Environment**: Testing performed on:
   Python 3.12
   OS: Windows 11

- **Commands**:
  Ran python -m unittest discover tests to ensure all test cases passed successfully.
  Validated compatibility with existing project components.

## Screenshots (if appropriate):
image
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by mikita-sakalouski** [comment]
Can you make these functionality based on Transformation step and also put it to the correct module ?

**Review by mikita-sakalouski — CHANGES_REQUESTED** [review]
See comments

**Comment by dannymeijer** [comment]
Thank you for your contribution @sritha272 , really appreciate it. 

I do agree with Mikita about the placement of the modules that you chose for this one. Also, can you explain the intended use for this a bit more? Would this be for ML usescases with the input being something like pandas perhaps? Or did you have something else in mind.

I propose that we have a small meetup to discuss, as I would love to add your contribution to our library.

**Review by dannymeijer — CHANGES_REQUESTED** [review]
See my earlier comment

**Comment by dannymeijer** [comment]
Please also see: https://github.com/Nike-Inc/koheesio/discussions/129

**Pull request closed without merging**
